### ISSUE TITLE
Audio data availability

### ISSUE THREAD

**Issue by cveaux** [marytts/enst-camille-data#16]
Hi the audio data doesn't seem to be online anymore. Is it possible to get a link to download it?

Thanks

**Comment by psibre** [comment]
The data is available as [Release Assets](https://github.com/marytts/enst-camille-data/releases).

Please see the [README](https://github.com/marytts/enst-camille-data#extracting-the-corpus) for how to extract the utterances.

Having said that, we're planning to streamline the process further soon by updating the build logic.

**Comment by cveaux** [comment]
Thanks
